mytestkey=This value is from LOCAL properties file

validation.rule-list=CHECK1,CHECK2
#validation.enabled=false
#validation.CHECK1.active=false
#
#validation.CHECK1.message=This is a message for CHECK1
#
#validation.CHECK2.active=false

